[package]
name = "wordle"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rayon = "1.10.0"
wasm-bindgen = "0.2.92"
wasm-bindgen-rayon = { version = "1.2.1", features = ["no-bundler"] }
